# Generated by Django 4.2.16 on 2026-01-05 18:18

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('inn', models.CharField(help_text='12 цифр для организаций, 10 для ИП', max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='9 символов, только для организаций', max_length=9, null=True, verbose_name='КПП')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('legal_address', models.TextField(max_length=500, verbose_name='Юридический адрес')),
                ('physical_address', models.TextField(blank=True, help_text='Если отличается от юридического', max_length=500, null=True, verbose_name='Фактический адрес')),
                ('phone', models.CharField(help_text='Формат: +7XXXXXXXXXX', max_length=20, verbose_name='Телефон')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('entrepreneur', 'Индивидуальный предприниматель'), ('organization', 'Юридическое лицо')], default='organization', max_length=20, verbose_name='Тип клиента')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('blocked', 'Заблокирован'), ('pending', 'Ожидает подтверждения')], default='pending', max_length=20, verbose_name='Статус')),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь', related_name='client_set', related_query_name='client', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Конкретные права пользователя', related_name='client_set', related_query_name='client', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['inn'], name='users_clien_inn_56d7f8_idx'), models.Index(fields=['status', 'registration_date'], name='users_clien_status_850bde_idx'), models.Index(fields=['client_type', 'status'], name='users_clien_client__e414ea_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
